apiVersion: v1 
kind: Secret
metadata: 
  name: rabbitmq
  labels: 
    project: roboshop
    component: rabbitmq
    tier: database
type: Opaque
data: 
  RABBITMQ_DEFAULT_USER: "cm9ib3Nob3A="
  RABBITMQ_DEFAULT_PASS: "cm9ib3Nob3AxMjM="

---
apiversion: v1
kind: Deployment
metadata: 
  name: rabbitmq
  namespace: roboshop
  labels:
    project: roboshop
    component: rabbitmq
    tier: database
spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      component: rabbitmq
      tier: database
  template:
    metadata:
      labels:
        project: roboshop
        component: rabbitmq
        tier: database
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3
        envFrom:
        - configMapRef:
            name: rabbitmq

---
apiVersion: v1 
kind: Service
metadata: 
  name: rabbitmq
  namespace: roboshop
  labels: 
    project: roboshop
    component: rabbitmq
    tier: database
spec: 
  selector:
    project: roboshop
    component: rabbitmq
    tier: database
  ports:
  - protocol: TCP
    port: 5672
    targetport: 5672
