# apiVersion: v1 
# kind: ConfigMap
# metadata: 
#   name: cart
#   namespace: roboshop
#   labels: 
#     project: roboshop
#     component: cart
#     tier: web
# data: 
#   REDIS_HOST: "redis"
#   CATALOGUE_HOST: "catalogue"
#   CATALOGUE_PORT: "8080"

---
apiversion: v1
kind: Deployment
metadata: 
  name: frontend
  namespace: roboshop
  labels:
    project: roboshop
    component: frontend
    tier: web
spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      component: frontend
      tier: web
  template:
    metadata:
      labels:
        project: roboshop
        component: frontend
        tier: web
    spec:
      containers:
      - name: frontend
        image: syamops/frontend:v1
        # envFrom:
        # - configMapRef:
        #     name: frontend
---

apiVersion: v1 
kind: Service
metadata: 
  name: frontend
  namespace: roboshop
  labels: 
    project: roboshop
    component: frontend
    tier: web
spec:
  type: LoadBalancerS
  selector:
    project: roboshop
    component: frontend
    tier: web
  ports:
  - protocol: TCP
    port: 80
    targetport: 80