apiVersion: v1 
kind: ConfigMap
metadata: 
  name: shipping
  namespace: roboshop
  labels: 
    project: roboshop
    component: shipping
    tier: app
data: 
  CART_ENDPOINT: "cart:8080"
  DB_HOST: "mysql"

---
apiversion: v1
kind: Deployment
metadata: 
  name: shipping
  namespace: roboshop
  labels:
    project: roboshop
    component: shipping
    tier: app
spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      component: shipping
      tier: app
  template:
    metadata:
      labels:
        project: roboshop
        component: shipping
        tier: app
    spec:
      containers:
      - name: shipping
        image: syamops/shipping:v1
        envFrom:
        - configMapRef:
            name: shipping

---
apiVersion: v1 
kind: Service
metadata: 
  name: shipping
  namespace: roboshop
  labels: 
    project: roboshop
    component: shipping
    tier: app
spec: 
  selector:
    project: roboshop
    component: shipping
    tier: app
  ports:
  - protocol: TCP
    port: 8080
    targetport: 8080