apiVersion: v1 
kind: ConfigMap
metadata: 
  name: user
  namespace: roboshop
  labels: 
    project: roboshop
    component: user
    tier: app
data: 
  MONGO: "true"
  REDIS_URL: "redis://redis:6379"
  MONGO_URL: "mongodb://mongodb:27017/users"

---
apiversion: v1
kind: Deployment
metadata: 
  name: user
  namespace: roboshop
  labels:
    project: roboshop
    component: user
    tier: app
spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      component: user
      tier: app
  template:
    metadata:
      labels:
        project: roboshop
        component: user
        tier: app
    spec:
      containers:
      - name: user
        image: syamops/user:v1
        envFrom:
        - configMapRef:
            name: user
---

apiVersion: v1 
kind: Service
metadata: 
  name: user
  namespace: roboshop
  labels: 
    project: roboshop
    component: user
    tier: app
spec: 
  selector:
    project: roboshop
    component: user
    tier: app
  ports:
  - protocol: TCP
    port: 8080
    targetport: 8080